pref("extensions.firefoxpasswordwarning.border",false);
pref("extensions.firefoxpasswordwarning.triangle",true);
pref("extensions.firefoxpasswordwarning.notbar",false);
pref("extensions.firefoxpasswordwarning.background",true);
pref("extensions.firefoxpasswordwarning.popup",false);
pref("extensions.firefoxpasswordwarning.popuponclick",true);
pref("extensions.firefoxpasswordwarning.statistics", true);
pref("extensions.firefoxpasswordwarning.debug", false);
pref("extensions.firefoxpasswordwarning.debug.verbose", false);
pref("extensions.firefoxpasswordwarning.usephishingwotdetection", true);
pref("extensions.firefoxpasswordwarning.styleokimage", "chrome://firefoxpasswordwarningextension/skin/check/orange/o_icon1.png");
pref("extensions.firefoxpasswordwarning.styleEVimage", "chrome://firefoxpasswordwarningextension/skin/check/gruen/gr_icon1.png");
pref("extensions.firefoxpasswordwarning.firstrun", true);
pref("extensions.firefoxpasswordwarning.starts", 0);
pref("extensions.firefoxpasswordwarning.exception_interval", 20);
pref("extensions.firefoxpasswordwarning.checkExceptionAuto", false);
pref("extensions.firefoxpasswordwarning.personalfields", false);
pref("extensions.firefoxpasswordwarning.searchfields", false);
pref("extensions.firefoxpasswordwarning.paymentfields", true);
pref("extensions.firefoxpasswordwarning.passwordfields", true);
pref("extensions.firefoxpasswordwarning.isbrokensecure", true);
pref("extensions.firefoxpasswordwarning.cookieBehavior_reset", -1);
pref("extensions.firefoxpasswordwarning.lifetimePolicy_reset", -1);
pref("extensions.firefoxpasswordwarning.httpToHttpsRedirects", "");
pref("extensions.firefoxpasswordwarning.userVerifiedDomains", "");
pref("extensions.firefoxpasswordwarning.pageExceptions", "");
