pref("extensions.firefoxwarning.border",false);
pref("extensions.firefoxwarning.triangle",true);
pref("extensions.firefoxwarning.notbar",false);
pref("extensions.firefoxwarning.background",true);
pref("extensions.firefoxwarning.popup",false);
pref("extensions.firefoxwarning.popuponclick",true);
pref("extensions.firefoxwarning.statistics", true);
pref("extensions.firefoxwarning.debug", false);
pref("extensions.firefoxwarning.debug.verbose", false);
pref("extensions.firefoxwarning.usephishingwotdetection", true);
pref("extensions.firefoxwarning.styleokimage", "chrome://firefoxpasswordwarningextension/skin/check/orange/o_icon1.png");
pref("extensions.firefoxwarning.styleEVimage", "chrome://firefoxpasswordwarningextension/skin/check/gruen/gr_icon1.png");
pref("extensions.firefoxwarning.firstrun", true);
pref("extensions.firefoxwarning.starts", 0);
pref("extensions.firefoxwarning.exception_interval", 20);
pref("extensions.firefoxwarning.checkExceptionAuto", false);
pref("extensions.firefoxwarning.personalfields", false);
pref("extensions.firefoxwarning.searchfields", false);
pref("extensions.firefoxwarning.paymentfields", true);
pref("extensions.firefoxwarning.passwordfields", true);
pref("extensions.firefoxwarning.isbrokensecure", true);
pref("extensions.firefoxwarning.cookieBehavior_reset", -1);
pref("extensions.firefoxwarning.lifetimePolicy_reset", -1);
pref("extensions.firefoxwarning.httpToHttpsRedirects", "");
pref("extensions.firefoxwarning.userVerifiedDomains", "");
pref("extensions.firefoxwarning.pageExceptions", "");
